# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bdd4e11a93bd639dc7011f5f7b9e6174b3bd66fa1e3a8eacdb439fd38d7389ff810064b0680fb1bb264b5c57e5ae6f7140a8b99b60b3880a8d9b22ee3c8ed89

test:
  secret_key_base: 14e6eba08ed2d796a796c0f32f17c474a4a14a08dc5c5350bf3460b94100ed52ed5c3d6386a4cc332daae47914d23f8108a7c2a58b2ce2802ec5a550e2cb9e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
